import Cocoa
import ImageIO
import SQLite3
import UniformTypeIdentifiers

@main
struct ClipboardRegression {
    static func require(_ condition: Bool, _ message: String) {
        guard condition else { fatalError(message) }
    }
    static func awaitResult<T>(_ operation: (@escaping (T) -> Void) -> Void) -> T {
        var value: T?
        operation { value = $0 }
        let deadline = Date().addingTimeInterval(10)
        while value == nil && Date() < deadline {
            RunLoop.main.run(until: Date().addingTimeInterval(0.01))
        }
        guard let value else { fatalError("Timed out waiting for background operation") }
        return value
    }
    static func load(_ manager: ClipboardManager, query: String = "", limit: Int = 1000, offset: Int = 0) throws -> [ClipboardItem] {
        let result: Result<[ClipboardItem], Error> = awaitResult { manager.load(query: query, limit: limit, offset: offset, completion: $0) }
        return try result.get()
    }
    static func main() throws {
        NSApplication.shared.setActivationPolicy(.prohibited)
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent("DashCat-regression-\(UUID())")
        let suite = "DashCat.regression.\(UUID())"
        let defaults = UserDefaults(suiteName: suite)!
        let pb = NSPasteboard.withUniqueName()
        defer {
            pb.releaseGlobally()
            defaults.removePersistentDomain(forName: suite)
            try? FileManager.default.removeItem(at: directory)
        }
        defaults.set(36500, forKey: "DashCatHistoryDays")
        let manager = ClipboardManager(directory: directory, defaults: defaults, pasteboard: pb)
        _ = try load(manager)
        func capture(_ value: String, type: String? = nil) throws {
            pb.clearContents()
            pb.setString(value, forType: .string)
            if let type { pb.setData(Data(), forType: .init(type)) }
            manager.checkPasteboard()
            _ = try load(manager)
        }
        let original = String(repeating: "a", count: 10000) + "TAIL\r\n\0结束"
        try capture(original)
        require(try load(manager).first?.content == original, "Long text/line endings/NUL lost")
        try capture(String(repeating: "a", count: 10000) + "DIFFERENT")
        require(try load(manager).count == 2, "Distinct suffix treated as duplicate")
        for type in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"] {
            try capture("synthetic-secret", type: type)
        }
        require(try load(manager).count == 2, "Confidential content captured")
        manager.setFilterTerms(["Secret", "secret", " "])
        try capture("A SECRET example")
        require(try load(manager).count == 2, "Filter terms not applied")
        manager.setFilterTerms([])
        try capture("École ПРИВЕТ %_\\")
        for query in ["école", "привет", "%_\\"] { require(try load(manager, query: query).count == 1, "Unicode/literal search failed") }
        require(try load(manager, query: "nonexistent").isEmpty, "False search result")
        print("PASS: complete text, deduplication, sensitive types, filters, Unicode and literal search")

        let context = CGContext(data: nil, width: 1600, height: 900, bitsPerComponent: 8, bytesPerRow: 0,
            space: CGColorSpaceCreateDeviceRGB(), bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
        context.setFillColor(CGColor(red: 1, green: 0, blue: 0, alpha: 0.5))
        context.fill(CGRect(x: 0, y: 0, width: 1600, height: 900))
        let data = NSMutableData()
        let destination = CGImageDestinationCreateWithData(data, UTType.png.identifier as CFString, 1, nil)!
        CGImageDestinationAddImage(destination, context.makeImage()!, nil)
        require(CGImageDestinationFinalize(destination), "PNG fixture failed")
        defaults.set(true, forKey: "DashCatSaveImages")
        pb.clearContents(); pb.setData(data as Data, forType: .png); manager.checkPasteboard()
        let image = try load(manager).first!
        let path = image.imagePath!
        require(try Data(contentsOf: URL(fileURLWithPath: path)) == data as Data, "Original image bytes changed")
        require(FileManager.default.fileExists(atPath: manager.thumbnailPath(for: path)!), "Thumbnail missing")
        let originalSource = CGImageSourceCreateWithURL(URL(fileURLWithPath: path) as CFURL, nil)!
        let decoded = CGImageSourceCreateImageAtIndex(originalSource, 0, nil)!
        require(decoded.width == 1600 && decoded.height == 900, "Original resolution lost")
        let pin: Bool = awaitResult { manager.togglePin(id: image.id, completion: $0) }
        require(pin, "Pin failed")
        print("PASS: exact PNG bytes, original dimensions, separate thumbnail and pin")

        var db: OpaquePointer?
        require(sqlite3_open(directory.appendingPathComponent("clipboard.db").path, &db) == SQLITE_OK, "Fixture DB failed")
        defer { sqlite3_close(db) }
        func sql(_ text: String) {
            require(sqlite3_exec(db, text, nil, nil, nil) == SQLITE_OK, "Fixture SQL failed: \(text)")
        }
        sql("UPDATE clipboard_history SET created_at=1")
        defaults.set(1, forKey: "DashCatHistoryDays")
        let cleaned: Bool = awaitResult { manager.cleanupExpired(completion: $0) }
        require(try cleaned && load(manager).count == 1, "Expiry did not preserve only pinned item")
        require(FileManager.default.fileExists(atPath: path), "Pinned image removed")
        sql("WITH RECURSIVE n(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM n WHERE x<201) INSERT INTO clipboard_history(content,created_at) SELECT 'fixture-'||x,2000000000+x FROM n")
        let page1 = try load(manager, limit: 200)
        let page2 = try load(manager, limit: 200, offset: 200)
        require(page1.count == 200 && page2.count == 2, "Pagination lost records")
        require(Set((page1 + page2).map(\.id)).count == 202, "Pagination duplicated records")
        let cleared: Bool = awaitResult { manager.clearAll(completion: $0) }
        require(try cleared && load(manager).count == 1, "Clear did not preserve pin")
        print("PASS: expiry, pinned preservation, pagination and scoped clear")

        // Legacy absolute paths resolve inside the current Images directory.
        let fileName = URL(fileURLWithPath: path).lastPathComponent
        sql("UPDATE clipboard_history SET image_path='/legacy/home/Images/\(fileName)'")
        require(try load(manager).first?.imagePath == path, "Legacy path did not resolve")
        let orphan = directory.appendingPathComponent("Images/orphan_thumb.jpg")
        try Data([1, 2, 3]).write(to: orphan)
        let orphanCleaned: Bool = awaitResult { manager.cleanupExpired(completion: $0) }
        require(orphanCleaned && !FileManager.default.fileExists(atPath: orphan.path), "Orphan thumbnail retained")

        // Sparse fixture checks the real 500 MB accounting without allocating 500 MB of RAM.
        let sparse = directory.appendingPathComponent("Images/pinned-large.tiff")
        require(FileManager.default.createFile(atPath: sparse.path, contents: Data()), "Sparse fixture failed")
        let handle = try FileHandle(forWritingTo: sparse)
        try handle.truncate(atOffset: 501 * 1024 * 1024)
        try handle.close()
        sql("INSERT INTO clipboard_history(image_path,is_pinned,created_at) VALUES('pinned-large.tiff',1,2000000000)")
        let largeID = sqlite3_last_insert_rowid(db)
        let overBudget: Bool = awaitResult { manager.cleanupExpired(completion: $0) }
        require(overBudget && FileManager.default.fileExists(atPath: sparse.path), "Budget removed a pinned image")
        let unpinned: Bool = awaitResult { manager.togglePin(id: largeID, completion: $0) }
        let reduced: Bool = awaitResult { manager.cleanupExpired(completion: $0) }
        require(unpinned && reduced && !FileManager.default.fileExists(atPath: sparse.path), "Budget failed to evict unpinned TIFF")
        require(FileManager.default.fileExists(atPath: path), "Budget removed another pinned original")
        print("PASS: legacy paths, orphan thumbnails, 500 MB budget and pinned overflow")

        // Synthetic large-history query: the main run loop must keep making progress.
        sql("WITH RECURSIVE n(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM n WHERE x<50000) INSERT INTO clipboard_history(content,created_at) SELECT 'bulk-history-'||x,2000000000+x FROM n")
        var ticks = 0
        let heartbeat = Timer.scheduledTimer(withTimeInterval: 0.001, repeats: true) { _ in ticks += 1 }
        let started = Date()
        let matches = try load(manager, query: "bulk-history-49999")
        heartbeat.invalidate()
        require(matches.count == 1 && ticks > 0, "Large search blocked the main run loop or lost result")
        print("PASS: 50,000-row search in \(String(format: "%.3f", Date().timeIntervalSince(started)))s; main-run-loop ticks: \(ticks)")
        sql("DELETE FROM clipboard_history WHERE content LIKE 'bulk-history-%'")

        // Exercise the real search-field delegate with an injected manager/pasteboard.
        let panel = ClipboardPanel(manager: manager, pasteboard: pb)
        _ = try load(manager) // Drain the panel's initial asynchronous query.
        let search = panel.contentView!.subviews.compactMap { $0 as? NSSearchField }.first!
        let table = panel.contentView!.subviews.compactMap { ($0 as? NSScrollView)?.documentView as? NSTableView }.first!
        let editor = NSTextView()
        let priorCount = pb.changeCount
        require(panel.control(search, textView: editor, doCommandBy: #selector(NSResponder.moveDown(_:))), "Search did not handle Down")
        require(table.selectedRow == 0 && pb.changeCount == priorCount, "Navigation copied or failed to select")
        search.stringValue = "no-such-history"
        require(panel.control(search, textView: editor, doCommandBy: #selector(NSResponder.moveDown(_:))), "Pending search command ignored")
        _ = try load(manager)
        require(table.numberOfRows == 0 && table.selectedRow == -1, "Navigation used stale search results")
        editor.setMarkedText("候选", selectedRange: NSRange(location: 0, length: 2), replacementRange: NSRange(location: NSNotFound, length: 0))
        require(!panel.control(search, textView: editor, doCommandBy: #selector(NSResponder.insertNewline(_:))), "IME confirmation was intercepted")
        if let output = ProcessInfo.processInfo.environment["DASHCAT_TEST_PREVIEW"], let view = panel.contentView {
            view.layoutSubtreeIfNeeded()
            if let bitmap = view.bitmapImageRepForCachingDisplay(in: view.bounds) {
                view.cacheDisplay(in: view.bounds, to: bitmap)
                try bitmap.representation(using: .png, properties: [:])?.write(to: URL(fileURLWithPath: output))
            }
        }
        panel.close()
        print("PASS: search keyboard navigation, stale search protection and IME command passthrough")

        // Query preparation failure must retain files even when their names look orphaned.
        sql("DROP TABLE clipboard_history")
        let failed: Bool = awaitResult { manager.cleanupExpired(completion: $0) }
        require(!failed, "Failed SQL reported success")
        require(FileManager.default.fileExists(atPath: path), "Failed query deleted valid image")
        // Specifically reach the SELECT guard via permanent retention (no DELETE first).
        defaults.set(36500, forKey: "DashCatHistoryDays")
        let failedSelect: Bool = awaitResult { manager.cleanupExpired(completion: $0) }
        require(!failedSelect && FileManager.default.fileExists(atPath: path), "Orphan scan failure deleted image")
        print("PASS: database failure fails closed and retains images")
        print("All clipboard regression checks passed; only temporary data was used.")
    }
}
